In [211]:
import pandas as pd
import numpy as np

In [208]:
df = pd.read_csv("year~AAPL~cash_flow_statement.csv")

In [203]:
df =  df.loc[:, 'date':'link']

In [214]:
df =  df.loc[:, 'date':'link']
L = ['other','Other']
df =  df.loc[:, ~df.columns.str.contains('|'.join(L))]

In [215]:
# original_df = df
# original_df

In [216]:
# all_titles = list(df)
# all_numbers_df = df[list(df.select_dtypes(include=['float','int64']))].div(4, axis=0)
# all_objects_df = df[list(df.select_dtypes(include=['object']))]
# concat_df = pd.concat([all_numbers_df, all_objects_df], axis=1)
# df = concat_df[all_titles]

In [217]:
# all_numbers_df = df[list(df.select_dtypes(include=['float','int64']))].div(4, axis=0)
df_row_1 = (df.select_dtypes(include=['float','int64']))[0:1].reset_index()
df_row_2 = (df.select_dtypes(include=['float','int64']))[1:2].reset_index()

In [218]:
df_yoy = (df_row_1.div(df_row_2))-1

In [219]:
# df[df["netIncome"]>1]
greater_than = (df_yoy[list(df_yoy)]>0.14) & (df_yoy[list(df_yoy)]<10)
less_than = (df_yoy[list(df_yoy)]<-0.14) & (df_yoy[list(df_yoy)]>-10)
not_zero = (df_yoy[list(df_yoy)] != -1)
df_yoyx = df_yoy[((greater_than) | (less_than)) & not_zero]

In [220]:
df_yoyx = df_yoyx.dropna(axis=1, how='all')

In [221]:
df_yoyx_sorted = df_yoyx.iloc[0].sort_values(ascending=False)

In [222]:
df_yoyx.sample(5, axis=1)

,acquisitionsNet,netCashUsedForInvestingActivites,netChangeInCash,debtRepayment,cashAtEndOfPeriod
0,1.442308,-1.09345,-1.42923,0.434299,-0.207769

In [226]:
df_dup = df_yoyx.sample(30, axis=1,replace=True)

In [228]:
df_dup.loc[:,~df_dup.columns.duplicated()]

['deferredIncomeTax',
 'cashAtEndOfPeriod',
 'netCashUsedForInvestingActivites',
 'capitalExpenditure',
 'changeInWorkingCapital',
 'debtRepayment',
 'netCashProvidedByOperatingActivities',
 'operatingCashFlow',
 'acquisitionsNet',
 'netChangeInCash',
 'freeCashFlow',
 'inventory',
 'investmentsInPropertyPlantAndEquipment']

In [ ]:
if len(df_dup)

In [225]:
list(df_yoyx.sample(30, axis=1,replace=True))

['inventory',
 'cashAtBeginningOfPeriod',
 'freeCashFlow',
 'cashAtEndOfPeriod',
 'cashAtBeginningOfPeriod',
 'netCashProvidedByOperatingActivities',
 'debtRepayment',
 'changeInWorkingCapital',
 'accountsPayables',
 'netChangeInCash',
 'operatingCashFlow',
 'netChangeInCash',
 'netChangeInCash',
 'accountsPayables',
 'operatingCashFlow',
 'capitalExpenditure',
 'cashAtBeginningOfPeriod',
 'accountsPayables',
 'freeCashFlow',
 'debtRepayment',
 'netCashProvidedByOperatingActivities',
 'freeCashFlow',
 'cashAtBeginningOfPeriod',
 'operatingCashFlow',
 'debtRepayment',
 'cashAtEndOfPeriod',
 'acquisitionsNet',
 'capitalExpenditure',
 'accountsPayables',
 'cashAtEndOfPeriod']

In [162]:
df_yoyx_5 = df_yoyx.sample(5, axis=1)

In [163]:
for x in list(df_yoyx_5):
    print(df_yoyx_5[x][0])

0.16260033721952416
-0.2077691940108315
0.16260033721952416
0.43429869392390685
-0.3035731300619342

In [148]:
df_yoyx.iloc[0].sort_values(ascending=False)

acquisitionsNet                           1.442308
accountsPayables                          1.112324
cashAtBeginningOfPeriod                   0.938178
debtRepayment                             0.434299
freeCashFlow                              0.245670
operatingCashFlow                         0.162600
netCashProvidedByOperatingActivities      0.162600
cashAtEndOfPeriod                        -0.207769
investmentsInPropertyPlantAndEquipment   -0.303573
otherWorkingCapital                      -0.328891
deferredIncomeTax                        -0.367647
inventory                                -0.560554
netCashUsedForInvestingActivites         -1.093450
netChangeInCash                          -1.429230
changeInWorkingCapital                   -1.450457
capitalExpenditure                       -1.696427
Name: 0, dtype: float64

In [167]:
df_yoyx_5

,netCashProvidedByOperatingActivities,cashAtEndOfPeriod,operatingCashFlow,debtRepayment,investmentsInPropertyPlantAndEquipment
0,0.1626,-0.207769,0.1626,0.434299,-0.303573

In [188]:
    company_profiles_col = ['symbol',
                            'long name',
                            'currency',
                            'exchange',
                            'industry',
                            'description',
                            'sector',
                            'country',
                            'ipo date',
                            'short name',
                            'Industries',
                            'Similar Companies',
                            'shortest name',
                            'url name']
    company_profiles = company_profiles[company_profiles_col]

    profiles_dict = {}
    profiles_value = company_profiles[company_profiles['symbol']=="{}".format(url_symbol.upper())].values.tolist()[0]
    for n, profiles_col in enumerate(company_profiles_col):
        key = profiles_col
        value = profiles_value[n]
        profiles_dict[key] = value

NameError: name 'company_profiles' is not defined

In [191]:
#     company_profiles_col = ['symbol',
#                             'long name',
#                             'currency',
#                             'exchange',
#                             'industry',
#                             'description',
#                             'sector',
#                             'country',
#                             'ipo date',
#                             'short name',
#                             'Industries',
#                             'Similar Companies',
#                             'shortest name',
#                             'url name']
#     company_profiles = company_profiles[company_profiles_col]

yoy_cards_dict = {}
profiles_value = df_yoyx_5.values.tolist()[0]
for n, profiles_col in enumerate(list(df_yoyx_5)):
    key = profiles_col
    value = profiles_value[n]
    yoy_cards_dict[key] = value

In [192]:
# list(profiles_dict.keys())[1]

yoy_1_key = list(yoy_cards_dict.items())[0][0]
yoy_1_value = list(yoy_cards_dict.items())[0][1]
yoy_2_key = list(yoy_cards_dict.items())[1][0]
yoy_2_value = list(yoy_cards_dict.items())[1][1]
yoy_3_key = list(yoy_cards_dict.items())[2][0]
yoy_3_value = list(yoy_cards_dict.items())[2][1]
yoy_4_key = list(yoy_cards_dict.items())[3][0]
yoy_4_value = list(yoy_cards_dict.items())[3][1]
yoy_5_key = list(yoy_cards_dict.items())[4][0]
yoy_5_value = list(yoy_cards_dict.items())[4][1]

In [180]:
next(iter(profiles_dict))

'netCashProvidedByOperatingActivities'

In [179]:
profiles_dict[1]

KeyError: 1

In [ ]:
        profiles_value = company_profiles[company_profiles['symbol']=="{}".format(url_symbol.upper())].values.tolist()[0]

In [170]:
list(df_yoyx_5)

['netCashProvidedByOperatingActivities',
 'cashAtEndOfPeriod',
 'operatingCashFlow',
 'debtRepayment',
 'investmentsInPropertyPlantAndEquipment']

In [172]:
yoy_cards_dict = {}

In [173]:
for n, key in enumerate(list(df_yoyx_5)):
    value = yoy_cards_dict[n]
    df_yoyx_5[key] = value

KeyError: 0

In [91]:
df_yoyx

,index,netIncome,depreciationAndAmortization,deferredIncomeTax,stockBasedCompensation,changeInWorkingCapital,accountsReceivables,inventory,accountsPayables,otherWorkingCapital,...,dividendsPaid,otherFinancingActivites,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.112324,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.938178,NaN,NaN,1.24567

In [92]:
df_yoy[df_yoy[list(df_yoy)]>.2]

,index,netIncome,depreciationAndAmortization,deferredIncomeTax,stockBasedCompensation,changeInWorkingCapital,accountsReceivables,inventory,accountsPayables,otherWorkingCapital,...,dividendsPaid,otherFinancingActivites,netCashUsedProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow
0,NaN,1.039,0.881167,0.632353,1.125412,NaN,28.232653,0.439446,2.112324,0.671109,...,0.997309,NaN,0.954318,NaN,NaN,0.792231,1.938178,1.1626,NaN,1.24567

In [94]:
# df_row_1.div(df_row_2).to_dict()

In [28]:
list(df)

['Unnamed: 0',
 'index',
 'date',
 'symbol',
 'filing_date',
 'accepted_date',
 'period',
 'net_revenue',
 'cost_of_sales',
 'gross_profit_margin_non',
 'gross_profit_margin_ratio',
 'r_n_d',
 'g_n_a',
 's_n_m',
 'other_income',
 'total_opex',
 'cost_expenses',
 'interest_expense',
 'd_n_a',
 'ebitda_non',
 'ebitda_margin',
 'operating_income',
 'operating_margin',
 'total_other_income',
 'pretax_income_non',
 'pretax_income_margin',
 'income_tax_expense',
 'net_income',
 'profit_margin',
 'eps_non',
 'eps_diluted',
 'shares_outstanding_non',
 'shares_outstanding_diluted',
 'sec_filing_link',
 'sec_statement_link',
 'cash_non',
 'short_term_investments',
 'cash_n_short_term_investments',
 'inventory',
 'other_current_assets',
 'total_current_assets',
 'pp_n_e',
 'goodwill',
 'intangible_assets',
 'goodwill_n_intangible_assets',
 'long_term_investments',
 'tax_assets',
 'other_assets',
 'total_assets',
 'accounts_payable',
 'short_term_debt',
 'income_tax_payables',
 'deferred_revenue',
 'other_current_liabilities',
 'total_current_liabilities',
 'long_term_debt',
 'deferred_revenue_non_current',
 'deferred_tax_liabilities_non_current',
 'other_non_current_liabilities',
 'total_non_current_liabilities',
 'other_liabilities',
 'total_liabilities',
 'common_stock',
 'retained_earnings',
 'accumulated_other_comprehensive_income',
 'other_se',
 'total_se',
 'total_l_se',
 'total_investments',
 'total_debt',
 'net_debt',
 'deferred_income_tax',
 'sbc',
 'change_in_working_capital',
 'accounts_receivable',
 'other_working_capital',
 'other_non_cash_items',
 'net_cash_by_operating_activities',
 'investments_in_pp_n_e',
 'acquisitions_net',
 'purchase_of_investments',
 'sales_maturities_of_investments',
 'other_investing_activities',
 'net_cash_used_for_investing_activities',
 'debt_repayment',
 'common_stock_issued',
 'common_stock_repurchased',
 'dividends_paid',
 'other_financing_activities',
 'net_cash_used_provided_by_financing_activities',
 'effect_of_fx_rate_changes_on_cash',
 'net_change_in_cash',
 'cash_at_end_of_period',
 'cash_at_beginning_of_period',
 'operating_cash_flow',
 'capex',
 'free_cash_flow',
 'QQ-YYYY',
 'Year',
 'ffo_math',
 'book_value_math',
 'ebit_math',
 'working_capital_math',
 'quick_assets_math',
 'quick_ratio_math']

In [29]:
 df.iloc[:, 0:2]

    Unnamed: 0  index
0         1727    0.0
1         1635    0.0
2         1551    0.0
3         1511    0.0
4         1431    0.0
5         1387    0.0
6         1299    0.0
7         1251    0.0
8         1195    0.0
9         1135    0.0
10        1071    0.0
11        1003    0.0
12         939    0.0
13         863    0.0
14         819    0.0
15         747    0.0
16         675    0.0
17         631    0.0
18         551    0.0
19         459    0.0
20         419    0.0
21         355    0.0
22         291    0.0
23         235    0.0
24         159    0.0
25         119    0.0
26          43    0.0

In [47]:
group_column = "symbol"

In [48]:
def replace(group, stds):
    group[np.abs(group - group.mean()) > stds * group.std()] = np.nan
    return group

# df is your DataFrame
# df.loc[:, df.columns != group_column] = 
# df.groupby(group_column).transform(lambda g: replace(g, 1))

In [49]:
df['pct_chg_temp'] = df['{}'.format("revenue_sales")]/df['{}'.format("revenue_sales")].shift(-4)

In [50]:
# df['pct_chg_temp'].values[df['pct_chg_temp'] > 10] = np.nan

In [51]:
df.loc[df['pct_chg_temp'] > 10, 'revenue_sales'] = np.nan

In [52]:
df.tail(30)

,Unnamed: 0,index,Unnamed: 0.1,date,symbol,filing_date,accepted_date,period,revenue_sales,cost_of_sales_cost_of_revenue_cost_of_goods_sold,...,income_tax_expense_provisions,net_income,net_income_ratio,eps_earnings_per_share,eps_earnings_per_share_diluted,shares_outstanding,shares_outstanding_weighted_diluted,sec_filing_url,sec_statement_url,pct_chg_temp
78,78,19,0.0,2001-06-30,AAPL,2001-12-21,2001-12-21 00:00:00,FY,1.340750e+09,1.032000e+09,...,-3750000.0,-6250000.0,-0.001166,-0.000323,-0.000323,4.839000e+09,4.839000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.671803
79,79,19,0.0,2001-03-31,AAPL,2001-12-21,2001-12-21 00:00:00,FY,1.340750e+09,1.032000e+09,...,-3750000.0,-6250000.0,-0.001166,-0.000323,-0.000323,4.839000e+09,4.839000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.671803
80,80,20,0.0,2000-12-31,AAPL,2000-12-14 00:00:00,2000-12-14 00:00:00,FY,NaN,1.454250e+09,...,76500000.0,196500000.0,0.024615,0.010804,0.009732,4.543952e+09,5.044536e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1301.434627
81,81,20,0.0,2000-09-30,AAPL,2000-12-14 00:00:00,2000-12-14 00:00:00,FY,NaN,1.454250e+09,...,76500000.0,196500000.0,0.024615,0.010804,0.009732,4.543952e+09,5.044536e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1301.434627
82,82,20,0.0,2000-06-30,AAPL,2000-12-14 00:00:00,2000-12-14 00:00:00,FY,NaN,1.454250e+09,...,76500000.0,196500000.0,0.024615,0.010804,0.009732,4.543952e+09,5.044536e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1301.434627
83,83,20,0.0,2000-03-31,AAPL,2000-12-14 00:00:00,2000-12-14 00:00:00,FY,NaN,1.454250e+09,...,76500000.0,196500000.0,0.024615,0.010804,0.009732,4.543952e+09,5.044536e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1301.434627
84,84,21,0.0,1999-12-31,AAPL,1999-12-22 00:00:00,1999-12-22 00:00:00,FY,1.533500e+06,1.109500e+09,...,18750000.0,150250000.0,0.024494,0.007703,0.007703,4.877000e+09,4.877000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.001032
85,85,21,0.0,1999-09-30,AAPL,1999-12-22 00:00:00,1999-12-22 00:00:00,FY,1.533500e+06,1.109500e+09,...,18750000.0,150250000.0,0.024494,0.007703,0.007703,4.877000e+09,4.877000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.001032
86,86,21,0.0,1999-06-30,AAPL,1999-12-22 00:00:00,1999-12-22 00:00:00,FY,1.533500e+06,1.109500e+09,...,18750000.0,150250000.0,0.024494,0.007703,0.007703,4.877000e+09,4.877000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.001032
87,87,21,0.0,1999-03-31,AAPL,1999-12-22 00:00:00,1999-12-22 00:00:00,FY,1.533500e+06,1.109500e+09,...,18750000.0,150250000.0,0.024494,0.007703,0.007703,4.877000e+09,4.877000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.001032
88,88,22,0.0,1998-12-31,AAPL,NaN,NaN,FY,1.485250e+09,1.115500e+09,...,5000000.0,77250000.0,0.013003,0.004108,0.004108,4.702000e+09,4.702000e+09,NaN,NaN,0.839006
89,89,22,0.0,1998-09-30,AAPL,NaN,NaN,FY,1.485250e+09,1.115500e+09,...,5000000.0,77250000.0,0.013003,0.004108,0.004108,4.702000e+09,4.702000e+09,NaN,NaN,0.839006
90,90,22,0.0,1998-06-30,AAPL,NaN,NaN,FY,1.485250e+09,1.115500e+09,...,5000000.0,77250000.0,0.013003,0.004108,0.004108,4.702000e+09,4.702000e+09,NaN,NaN,0.839006
91,91,22,0.0,1998-03-31,AAPL,NaN,NaN,FY,1.485250e+09,1.115500e+09,...,5000000.0,77250000.0,0.013003,0.004108,0.004108,4.702000e+09,4.702000e+09,NaN,NaN,0.839006
92,92,23,0.0,1997-12-31,AAPL,1997-12-05 00:00:00,1997-12-05 00:00:00,FY,1.770250e+09,1.428250e+09,...,0.0,-261250000.0,-0.036894,-0.018503,-0.018503,3.530000e+09,3.530000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.720126
93,93,23,0.0,1997-09-30,AAPL,1997-12-05 00:00:00,1997-12-05 00:00:00,FY,1.770250e+09,1.428250e+09,...,0.0,-261250000.0,-0.036894,-0.018503,-0.018503,3.530000e+09,3.530000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.720126
94,94,23,0.0,1997-06-30,AAPL,1997-12-05 00:00:00,1997-12-05 00:00:00,FY,1.770250e+09,1.428250e+09,...,0.0,-261250000.0,-0.036894,-0.018503,-0.018503,3.530000e+09,3.530000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.720126
95,95,23,0.0,1997-03-31,AAPL,1997-12-05 00:00:00,1997-12-05 00:00:00,FY,1.770250e+09,1.428250e+09,...,0.0,-261250000.0,-0.036894,-0.018503,-0.018503,3.530000e+09,3.530000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.720126
96,96,24,0.0,1996-12-31,AAPL,1996-12-19 00:00:00,1996-12-19 00:00:00,FY,2.458250e+09,2.216250e+09,...,-119750000.0,-204000000.0,-0.020747,-0.014717,-0.014717,3.465000e+09,3.465000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.888899
97,97,24,0.0,1996-09-30,AAPL,1996-12-19 00:00:00,1996-12-19 00:00:00,FY,2.458250e+09,2.216250e+09,...,-119750000.0,-204000000.0,-0.020747,-0.014717,-0.014717,3.465000e+09,3.465000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.888899
98,98,24,0.0,1996-06-30,AAPL,1996-12-19 00:00:00,1996-12-19 00:00:00,FY,2.458250e+09,2.216250e+09,...,-119750000.0,-204000000.0,-0.020747,-0.014717,-0.014717,3.465000e+09,3.465000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.888899
99,99,24,0.0,1996-03-31,AAPL,1996-12-19 00:00:00,1996-12-19 00:00:00,FY,2.458250e+09,2.216250e+09,...,-119750000.0,-204000000.0,-0.020747,-0.014717,-0.014717,3.465000e+09,3.465000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,0.888899
100,100,25,0.0,1995-12-31,AAPL,1995-12-19 00:00:00,1995-12-19 00:00:00,FY,2.765500e+09,2.051000e+09,...,62500000.0,106000000.0,0.009582,0.007692,0.007692,3.445000e+09,3.445000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1.203864
101,101,25,0.0,1995-09-30,AAPL,1995-12-19 00:00:00,1995-12-19 00:00:00,FY,2.765500e+09,2.051000e+09,...,62500000.0,106000000.0,0.009582,0.007692,0.007692,3.445000e+09,3.445000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1.203864
102,102,25,0.0,1995-06-30,AAPL,1995-12-19 00:00:00,1995-12-19 00:00:00,FY,2.765500e+09,2.051000e+09,...,62500000.0,106000000.0,0.009582,0.007692,0.007692,3.445000e+09,3.445000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1.203864
103,103,25,0.0,1995-03-31,AAPL,1995-12-19 00:00:00,1995-12-19 00:00:00,FY,2.765500e+09,2.051000e+09,...,62500000.0,106000000.0,0.009582,0.007692,0.007692,3.445000e+09,3.445000e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,1.203864
104,104,26,0.0,1994-12-31,AAPL,1994-12-13 00:00:00,1994-12-13 00:00:00,FY,2.297187e+09,1.711229e+09,...,47527000.0,77544500.0,0.008439,0.005826,0.005826,3.324580e+09,3.326680e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,NaN
105,105,26,0.0,1994-09-30,AAPL,1994-12-13 00:00:00,1994-12-13 00:00:00,FY,2.297187e+09,1.711229e+09,...,47527000.0,77544500.0,0.008439,0.005826,0.005826,3.324580e+09,3.326680e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,NaN
106,106,26,0.0,1994-06-30,AAPL,1994-12-13 00:00:00,1994-12-13 00:00:00,FY,2.297187e+09,1.711229e+09,...,47527000.0,77544500.0,0.008439,0.005826,0.005826,3.324580e+09,3.326680e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,NaN
107,107,26,0.0,1994-03-31,AAPL,1994-12-13 00:00:00,1994-12-13 00:00:00,FY,2.297187e+09,1.711229e+09,...,47527000.0,77544500.0,0.008439,0.005826,0.005826,3.324580e+09,3.326680e+09,https://www.sec.gov/Archives/edgar/data/320193...,https://www.sec.gov/Archives/edgar/data/320193...,NaN